In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.svm import LinearSVR
from sklearn.neighbors import KNeighborsRegressor as KN
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

from sklearn.model_selection import GridSearchCV

In [3]:
train = pd.read_csv(r'C:\Users\Fran Pantoni.DESKTOP-VKGKGM6\Desktop\Facultad\Ciencia de Datos\clase_08\Desafio/Xy_train.csv', delimiter=',', parse_dates = True)

In [4]:
train.head()

X         y
0  2.273360  6.054685
1  3.167583  4.581428
2  7.973655  5.392507
3  6.762547  3.108068
4  3.911096  4.225744

In [5]:
np.shape(train)

(100, 2)

In [6]:
train.isnull().sum()

X    0
y    0
dtype: int64

In [28]:
test = pd.read_csv(r'C:\Users\Fran Pantoni.DESKTOP-VKGKGM6\Desktop\Facultad\Ciencia de Datos\clase_08\Desafio/X_test.csv', delimiter=',', parse_dates = True)

In [29]:
test.head()

X
0  6.170800
1  6.302022
2  8.689293
3  2.376897
4  2.707320

In [30]:
np.shape(test)

(20, 1)

In [31]:
test.isnull().sum()

X    0
dtype: int64

In [32]:
#Definimos la X e Y de entrenamiento
x = train.iloc[:,0:1]
y = train.iloc[:,1:]

In [33]:
x

X
0   2.273360
1   3.167583
2   7.973655
3   6.762547
4   3.911096
..       ...
95  3.787495
96  2.759471
97  9.661041
98  0.582026
99  4.087339

[100 rows x 1 columns]

In [34]:
y

y
0    6.054685
1    4.581428
2    5.392507
3    3.108068
4    4.225744
..        ...
95   5.133706
96   4.308327
97  11.923565
98   1.335725
99   5.641851

[100 rows x 1 columns]

In [111]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.80, random_state=10)

In [112]:
xtrain.head()

X
49  6.286045
78  6.180567
72  7.505313
33  7.247814
62  2.790671

In [113]:
np.shape(xtrain)

(20, 1)

In [114]:
#Escalamos
scaler = preprocessing.StandardScaler().fit(xtrain)
scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [115]:
xtrain_scal = scaler.transform(xtrain)

In [116]:
xtest_scal = scaler.transform(xtest)

## Creamos modelo de Regresión Lineal

In [143]:
lr=LinearRegression()

In [144]:
lr.fit(xtrain_scal, ytrain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [145]:
ypred = lr.predict(xtest_scal)

In [146]:
ypred

array([[2.90528838],
       [4.68768511],
       [8.39883715],
       [8.67394068],
       [5.12013771],
       [6.57226634],
       [5.45247274],
       [6.48209725],
       [5.11497106],
       [7.87649945],
       [7.54593744],
       [3.68209282],
       [3.18745418],
       [2.55308852],
       [4.18047119],
       [2.81701522],
       [8.12988886],
       [2.68950344],
       [4.96528279],
       [3.2165656 ],
       [1.21359244],
       [8.06682385],
       [3.40572966],
       [3.20226152],
       [3.13944398],
       [4.68002462],
       [2.42099363],
       [3.52778997],
       [5.94561954],
       [3.23044029],
       [3.79571189],
       [8.05392065],
       [1.78567993],
       [6.09451302],
       [8.60693012],
       [3.33651332],
       [3.86756425],
       [4.27983995],
       [3.81117184],
       [1.1758888 ],
       [8.62823931],
       [1.79149188],
       [6.64115137],
       [4.94891644],
       [3.99312642],
       [6.23679409],
       [3.76019281],
       [3.115

In [147]:
lr_mse=(mean_squared_error(ytest, ypred))

In [148]:
lr_mae=mean_absolute_error(ytest, ypred)

In [149]:
lr_r2=np.sqrt(mean_squared_error(ytest, ypred))

In [171]:
resultados_finales= pd.DataFrame(columns=['Modelo','R2','MSE','MAE'])

In [172]:
resultados_finales = resultados_finales.append({'Modelo': 'Regresion Lineal',
                               'MSE':lr_mse,
                               'MAE':lr_mae,
                               'R2':lr_r2},ignore_index=True)

In [173]:
resultados_finales

Modelo        R2       MSE       MAE
0  Regresion Lineal  1.843953  3.400162  1.575851

## Support Vector Regression

In [174]:
svr=SVR()

In [175]:
svr.fit(xtrain_scal, ytrain)

C:\Users\Fran Pantoni.DESKTOP-VKGKGM6\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [176]:
ypred = svr.predict(xtest_scal)
ypred

array([4.80414687, 4.89905044, 7.71813772, 8.12436259, 4.58281218,
       4.19600491, 4.31886658, 4.12852507, 4.58696524, 6.62804293,
       5.85258644, 5.10736408, 4.93703332, 4.64271307, 5.11201098,
       4.76185209, 7.19560909, 4.70235783, 4.70483168, 4.94994394,
       4.5625736 , 7.05948594, 5.02679559, 4.94362935, 4.91527057,
       4.9037718 , 4.59083651, 5.06787663, 4.0437943 , 4.95601246,
       5.12603966, 7.03113694, 4.46614324, 4.01748327, 8.03918531,
       5.00028942, 5.13280163, 5.08746818, 5.12783573, 4.57514136,
       8.06727901, 4.46617784, 4.25863042, 4.71731557, 5.13455397,
       4.02605612, 5.12122275, 4.90414863, 4.63621062, 4.67869259,
       4.0168503 , 8.34261057, 4.47589032, 5.03747755, 4.97610601,
       4.91152039, 5.00717766, 4.96052485, 4.56363949, 4.64936872,
       4.77201949, 5.13294316, 4.76525087, 4.89928586, 4.79717903,
       4.51553578, 5.10104014, 4.79561519, 4.03665391, 4.77267858,
       4.1404622 , 4.91121964, 6.92726111, 5.19117047, 6.19903

In [177]:
svr_mse=(mean_squared_error(ytest, ypred))

In [178]:
svr_mae=mean_absolute_error(ytest, ypred)

In [179]:
svr_r2=np.sqrt(mean_squared_error(ytest, ypred))

In [180]:
resultados_finales = resultados_finales.append({'Modelo': 'Supoort Vector Regression',
                               'MSE':svr_mse,
                               'MAE':svr_mae,
                               'R2':svr_r2},ignore_index=True)

In [181]:
resultados_finales

Modelo        R2       MSE       MAE
0           Regresion Lineal  1.843953  3.400162  1.575851
1  Supoort Vector Regression  1.308064  1.711031  0.951590

## KNN Regression

In [183]:
knn=KN()

In [184]:
knn.fit(xtrain_scal, ytrain)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                    weights='uniform')

In [185]:
ypred = knn.predict(xtest_scal)
ypred

array([[ 4.69348447],
       [ 4.40743423],
       [10.40901826],
       [10.40901826],
       [ 4.37109419],
       [ 3.74263626],
       [ 4.16838937],
       [ 4.12156397],
       [ 4.37109419],
       [ 8.43069378],
       [ 5.13472176],
       [ 4.92932979],
       [ 4.69348447],
       [ 4.69348447],
       [ 4.97201083],
       [ 4.69348447],
       [10.40901826],
       [ 4.69348447],
       [ 4.37109419],
       [ 4.69348447],
       [ 4.69348447],
       [10.40901826],
       [ 4.92932979],
       [ 4.69348447],
       [ 4.69348447],
       [ 4.40743423],
       [ 4.69348447],
       [ 4.92932979],
       [ 3.84620269],
       [ 4.69348447],
       [ 4.97201083],
       [10.40901826],
       [ 4.69348447],
       [ 3.86655841],
       [10.40901826],
       [ 4.92932979],
       [ 4.97201083],
       [ 4.67056264],
       [ 4.97201083],
       [ 4.69348447],
       [10.40901826],
       [ 4.69348447],
       [ 4.13315263],
       [ 4.37109419],
       [ 4.97201083],
       [ 3

In [186]:
knn_mse=(mean_squared_error(ytest, ypred))

In [187]:
knn_mae=mean_absolute_error(ytest, ypred)

In [188]:
knn_r2=np.sqrt(mean_squared_error(ytest, ypred))

In [189]:
resultados_finales = resultados_finales.append({'Modelo': 'KNN Regression',
                               'MSE':knn_mse,
                               'MAE':knn_mae,
                               'R2':knn_r2},ignore_index=True)

In [190]:
resultados_finales

Modelo        R2       MSE       MAE
0           Regresion Lineal  1.843953  3.400162  1.575851
1  Supoort Vector Regression  1.308064  1.711031  0.951590
2             KNN Regression  1.447782  2.096072  1.037037

In [198]:
print("El de menor MSE es el correspondiente al modelo de Supoort Vector Regression con un valor igual a "+str (svr_mse))

El de menor MSE es el correspondiente al modelo de Supoort Vector Regression con un valor igual a 1.711031227097036


### Voy con el SVR

In [199]:
svr=SVR()

In [200]:
svr.fit(xtrain_scal, ytrain)

C:\Users\Fran Pantoni.DESKTOP-VKGKGM6\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [202]:
test_scal = scaler.transform(test)

In [203]:
ypred = svr.predict(test_scal)
ypred

array([4.01736425, 4.02069844, 7.17727012, 4.87180603, 4.99044646,
       4.08433486, 6.82755036, 4.55896384, 7.83502075, 4.97986257,
       5.11848505, 4.03964237, 7.88247369, 4.47020589, 4.75405749,
       6.10768759, 4.57915014, 4.03712849, 4.55397523, 4.01878768])